server:
  port: 8080

spring:
  profiles:
    active: local
  application:
    name: plant-disease-java-res
  datasource:
    url: jdbc:mysql://localhost:3306/plant_disease?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

jwt:
  secret: ${app.jwt-secret}
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs

aliyun:
  oss:
    endpoint: ${aliyun.oss.endpoint}
    bucket-name: ${aliyun.oss.bucket-name}
    region: ${aliyun.oss.region}
    access-key-id: ${aliyun.oss.access-key-id}
    access-key-secret: ${aliyun.oss.access-key-secret}